### PR TITLE
Migrate To AndroidX

### PR DESCRIPTION
**Pull request by popkter**
(cherry picked from commit e6a959e8cd8522b3df9219b3df47ed85f3fd1c38)

### CODE REVIEW

**Comment by popkter** [comment]
just migrate to AndroidX

**Comment by getActivity** [comment]
https://github.com/getActivity/ShapeView/issues/31

**Comment by popkter** [comment]
> #31

got it. thanks

**Comment by w-xuedinger** [comment]
老哥，2026了，还不升级androidx吗

**Pull request closed without merging**
